/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 * The admin class is the essential class that is used by the inventory's administrator to perform multiple operations
 * such as Create, read, update, and delete.
 * The logic of data structure and algorithm is also implemented here which runs based on the admin's command.
 * 
 * @author ruzalrajopadhyay
 */
// importing essential 
import java.awt.*;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.*;
import Model.Product;
import Model.ProductStored;
import Model.CategoryStored;
import java.time.LocalDate;
import Controller.Search;
import Controller.Sorting;
import Model.RecentlyAddedQueue;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import Model.BinManager;
public class Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());
    
    /**
     * Creates new form Admin
     */
    // Declaring variables
    private Login login;
    private CardLayout cardLayout;
    static ProductStored productStored = new ProductStored();
    static CategoryStored categoryStored = new CategoryStored(productStored.getAllProducts());
    
    // Constructor of the admin class
    public Admin(Login login) {
        // initializing parameters
        this.login = login;
        initComponents();
        // Setting up card layout
        
        RecentlyAddedQueue.initializingTable();
        RecentlyAddedQueue.updateTable(recentlyAdded);
        productStored.populatingTable(productListTable, productStored.getAllProducts());
        TotalItemText();
        productStored.refreshTable(productListTable);
        searchAction();
        
        jPanel3.setLayout(new java.awt.CardLayout());
        cardLayout = (CardLayout) jPanel3.getLayout();
        
        // Adding panels in the card layouy
        jPanel3.add(Dashboard, "Dashboard");
        jPanel3.add(viewProduct, "viewProduct");
        jPanel3.add(addProduct, "addProduct");
        cardLayout.show(jPanel3, "Dashboard");
        comboData();
        
    }
    /*
    The method is used to update the expiry da
    */
    private void updateExpiry(){
        
        boolean isFood = "Food".equalsIgnoreCase(category.getSelectedItem().toString());
        comboDay.setEnabled(isFood);
        comboMonth.setEnabled(isFood);
        comboYear.setEnabled(isFood);
        if(!isFood){
            comboDay.setSelectedItem(0);
            comboMonth.setSelectedItem(0);
            comboYear.setSelectedItem(0);
            
        }
        this.revalidate();
        this.repaint();
        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        view = new javax.swing.JButton();
        update = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productNum = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        itemCategory = new javax.swing.JComboBox<>();
        TotalItems = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recentlyAdded = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        bin = new javax.swing.JTable();
        Restore = new javax.swing.JButton();
        removeFromBin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        viewProduct = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sortBy = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        idSearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        searchName = new javax.swing.JTextField();
        idButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productListTable = new javax.swing.JTable();
        addProduct = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        priceStr = new javax.swing.JTextField();
        category = new javax.swing.JComboBox<>();
        comboDay = new javax.swing.JComboBox<>();
        comboMonth = new javax.swing.JComboBox<>();
        comboYear = new javax.swing.JComboBox<>();
        productId = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        uploadBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(143, 26, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 179, 66));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel2.setText("Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        dashboard.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        dashboard.setText("🖥 Dashboard");
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 40));

        view.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        view.setText("View Products");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, 40));

        update.setText("Update System");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 140, 40));

        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel1.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jPanel3.setBackground(new java.awt.Color(143, 1, 119));
        jPanel3.setLayout(new java.awt.CardLayout());

        Dashboard.setBackground(new java.awt.Color(143, 1, 119));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(245, 245, 245))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(129, 2, 158));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Product Number");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        itemCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Electronic", "Food", "Shoes" }));
        itemCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemCategoryItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemCategory, 0, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        TotalItems.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        TotalItems.setText("120");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Category");

        javax.swing.GroupLayout productNumLayout = new javax.swing.GroupLayout(productNum);
        productNum.setLayout(productNumLayout);
        productNumLayout.setHorizontalGroup(
            productNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productNumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productNumLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TotalItems))
                    .addGroup(productNumLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        productNumLayout.setVerticalGroup(
            productNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productNumLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalItems))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        recentlyAdded.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product Id", "Product Name"
            }
        ));
        jScrollPane2.setViewportView(recentlyAdded);

        bin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product Id", "Product Name"
            }
        ));
        bin.setToolTipText("");
        jScrollPane3.setViewportView(bin);

        Restore.setText("Restore item");
        Restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoreActionPerformed(evt);
            }
        });

        removeFromBin.setText("Remove from bin");
        removeFromBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromBinActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recently Added Section");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recycle Bin");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(Restore, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeFromBin)
                        .addGap(19, 19, 19))))
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(98, 98, 98)
                .addComponent(productNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(productNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(7, 7, 7)))
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Restore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(removeFromBin, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.add(Dashboard, "card2");

        viewProduct.setBackground(new java.awt.Color(143, 1, 119));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jLabel3.setText("Product List");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sort By:");

        sortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Product Id", "Name", "Price", "Electronic", "Food", "Shoes" }));
        sortBy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortByItemStateChanged(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search Id:");

        idSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSearchActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search Product:");

        searchName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                searchNameInputMethodTextChanged(evt);
            }
        });
        searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameActionPerformed(evt);
            }
        });

        idButton.setText("Search");
        idButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idButtonActionPerformed(evt);
            }
        });

        productListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Category", "Quantity", "Price", "Expiry Date"
            }
        ));
        jScrollPane1.setViewportView(productListTable);

        javax.swing.GroupLayout viewProductLayout = new javax.swing.GroupLayout(viewProduct);
        viewProduct.setLayout(viewProductLayout);
        viewProductLayout.setHorizontalGroup(
            viewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(viewProductLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(viewProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        viewProductLayout.setVerticalGroup(
            viewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProductLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(viewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(sortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(idSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idButton))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(viewProduct, "card3");

        addProduct.setBackground(new java.awt.Color(143, 1, 119));

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jLabel11.setText("Update System");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(239, 239, 239))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jLabel13.setText("Product Id: ");

        jLabel14.setText("Product Name: ");

        jLabel15.setText("Category: ");

        jLabel16.setText("Quantity:");

        jLabel17.setText("Price: ");

        jLabel18.setText("Expiry Date:");

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronic", "Food", "Shoes" }));
        category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categoryItemStateChanged(evt);
            }
        });
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        comboDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDayActionPerformed(evt);
            }
        });

        comboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(38, 38, 38)
                        .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceStr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(priceStr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        uploadBtn.setText("Upload");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addProductLayout = new javax.swing.GroupLayout(addProduct);
        addProduct.setLayout(addProductLayout);
        addProductLayout.setHorizontalGroup(
            addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addProductLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(addProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        addProductLayout.setVerticalGroup(
            addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        jPanel3.add(addProduct, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        cardLayout.show(jPanel3, "Dashboard");   // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        cardLayout.show(jPanel3, "viewProduct");// TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        cardLayout.show(jPanel3, "addProduct");
        updateExpiry();
// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // Operations that will take place after clicking log out button
        this.setVisible(false);
        login.setVisible(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_logOutActionPerformed

    private void idSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSearchActionPerformed

    private void searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameActionPerformed

    private void idButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idButtonActionPerformed
        String id = idSearch.getText().trim();
        
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Make sure you entered correct Id", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Product found  = Controller.Search.binarySearchId(productStored.getAllProducts(), id);
        if(found != null){
            String message = String.format("Product Information: \n"
                    + "ID: %s\n"
                    + "Name: %s\n"
                    + "Category: %s\n"
                    + "Quantity in Stock: %d\n"
                    + "Price: $%.2f \n"
                    + "Expiry Date: %s",
                    found.getProductId(),
                    found.getProductName(),
                    found.getCategory(),
                    found.getQuantity(),
                    found.getPrice(),
                    found.getExpiryDate());
            JOptionPane.showMessageDialog(this, message, "Product Details", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Product not Found", "No match found", JOptionPane.ERROR_MESSAGE);
        }
    


        // TODO add your handling code here:
    }//GEN-LAST:event_idButtonActionPerformed

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        try{
            String id = productId.getText().trim();
            String name = productName.getText().trim();
            String ctg = category.getSelectedItem().toString();
            if(id.isEmpty() || name.isEmpty() || quantity.getText().isEmpty()  || priceStr.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "The fields must not be empty", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int idInt = Integer.parseInt(id);
            
            if(id.length() > 3){
                JOptionPane.showMessageDialog(this, "The length of your product id can only be 3 characters long", "Warning"
                , JOptionPane.WARNING_MESSAGE);
                return;
            }
            id = id = "P" + String.format("%03d", idInt);
            for(Product p: productStored.getAllProducts()){
                if(id.equalsIgnoreCase(p.getProductId())){
                    JOptionPane.showMessageDialog(this, "The product id already exists in the system, Choose another",
                            "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            if(ctg.equalsIgnoreCase("Food")){
                if(comboYear.getSelectedIndex() == 0){
                    JOptionPane.showMessageDialog(this, "The expiry date of the food item must be set", "Error",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            
            int qty = Integer.parseInt(quantity.getText().trim());
            double price = Double.parseDouble(priceStr.getText().trim());
            int year = Integer.parseInt(comboYear.getSelectedItem().toString());
            int month = Integer.parseInt(comboMonth.getSelectedItem().toString());
            int day = Integer.parseInt(comboDay.getSelectedItem().toString());
            LocalDate expiry = LocalDate.of(year, month, day);
            
            if(ctg .equalsIgnoreCase("Food") && expiry.isBefore(LocalDate.now())){
                JOptionPane.showMessageDialog(this, "Food expiry date cannot be in the past", "Invalid Date",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            
           
            if (qty <= 0 || price <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity or price cannot be zero or negative.", "Error",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            Product newProduct = new Product(id, name, ctg, qty, price, expiry);
            productStored.addProduct(newProduct);
            categoryStored.addProduct(newProduct);
            RecentlyAddedQueue.enqueue(newProduct);
            
            productId.setText("");
            productName.setText("");
            quantity.setText("");
            priceStr.setText("");
            comboDay.setSelectedIndex(0);
            comboMonth.setSelectedIndex(0);
            comboYear.setSelectedIndex(0);
            
            productStored.refreshTable(productListTable);
            RecentlyAddedQueue.updateTable(recentlyAdded);
            
            JOptionPane.showMessageDialog(this, "Product Added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            
            
        }  
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter numeric data in id, quantity, and price fields", "Warning",
                    JOptionPane.WARNING_MESSAGE);
        }
        catch(java.time.DateTimeException e){
            JOptionPane.showMessageDialog(this, "Please enter a valid date", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "An error Occured", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void comboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboYearActionPerformed

    private void comboDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDayActionPerformed

    private void categoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categoryItemStateChanged
            updateExpiry();  // TODO add your handling code here:
    }//GEN-LAST:event_categoryItemStateChanged

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String id = productId.getText().trim();
        
        
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please make sure you have entered Id", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Product productToDelete = productStored.searchById(id);
        if(productToDelete != null){
            int confirmation = JOptionPane.showConfirmDialog(this, "This process cannot be undone, Are you sure?",
                    "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if(confirmation == JOptionPane.YES_OPTION){
                boolean isDeleted = productStored.deleteProduct(id);
                if(isDeleted){
                    Model.BinManager.push(productToDelete);
                    JOptionPane.showMessageDialog(this, "Product Successfully deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
                    Model.RecentlyAddedQueue.productDeletion(id);
                    
                    
                    productStored.refreshTable(productListTable);
                    Model.BinManager.refreshBinTable(bin);
                    Model.RecentlyAddedQueue.updateTable(recentlyAdded);
                    productId.setText("");
                    productName.setText("");
                    quantity.setText("");
                    priceStr.setText("");
            }
                else{
                    JOptionPane.showMessageDialog(this, "Product Id not found. Please enter correct product id", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
            String id = productId.getText().trim();
            
            
            
            if(id.isEmpty() || quantity.getText().isEmpty() || priceStr.getText().isEmpty() ){
                JOptionPane.showMessageDialog(this, "Please make sure you have entered details to update", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            try{
                int qty = Integer.parseInt(quantity.getText().trim());
                double price = Double.parseDouble(priceStr.getText().trim());
                if(qty <= 0 || price <= 0){
                    JOptionPane.showMessageDialog(this, "Quantity or price cannot be zero or negative.", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                }
            
                int confirmation = JOptionPane.showConfirmDialog(this, "Only the quantity and price of the product will change.",
                        "Confirm Update", JOptionPane.YES_NO_OPTION);
                if(confirmation == JOptionPane.YES_OPTION){
                    boolean updated = productStored.updateProduct(id, qty, price);
                    if(updated){
                        JOptionPane.showMessageDialog(this, "Product Successfully Updated", "Success",
                                JOptionPane.INFORMATION_MESSAGE);
                        productStored.refreshTable(productListTable);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Please enter correct product id", "Warning",
                                JOptionPane.WARNING_MESSAGE);
                    }
                }
                productId.setText("");
                productName.setText("");
                quantity.setText("");
                priceStr.setText("");
            
        }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Make sure the price and quantity are numeric", "Warning", JOptionPane.WARNING_MESSAGE);
            }



        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void sortByItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortByItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            String selectedOption = sortBy.getSelectedItem().toString();
            ArrayList<Product> productListCopy = new ArrayList<Product>(productStored.getAllProducts());
            if (selectedOption.equalsIgnoreCase("Product Id")){
                Sorting.selectionSortId(productListCopy);
            }
            else if(selectedOption.equalsIgnoreCase("Electronic") ||selectedOption.equalsIgnoreCase("Food") || selectedOption.equalsIgnoreCase("Shoes")) {
                productListCopy = new ArrayList<Product>(categoryStored.getByCategory(selectedOption));
            }
            else if(selectedOption.equalsIgnoreCase("Name")){
                Sorting.mergeSortName(productListCopy);
            }
            else if(selectedOption.equalsIgnoreCase("Price")){
                Sorting.insertionSortPrice(productListCopy);
            }
            
            productStored.populatingTable(productListTable, productListCopy);
        }
    }//GEN-LAST:event_sortByItemStateChanged

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void removeFromBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromBinActionPerformed
       int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to permanently delete the last item from the bin?.", 
            "Confirm Permanent Deletion", JOptionPane.YES_NO_OPTION);
       if(confirm == JOptionPane.YES_OPTION){
           Product deletedItem = BinManager.pop();
           if(deletedItem == null){
               JOptionPane.showMessageDialog(this, "The Table is empty", "Warning", JOptionPane.WARNING_MESSAGE);
               return;
           }
           JOptionPane.showMessageDialog(this, "The product " + deletedItem.getProductName() + " Has been deleted from the bin",
                   "Success", JOptionPane.INFORMATION_MESSAGE);
           BinManager.refreshBinTable(bin);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_removeFromBinActionPerformed

    private void searchNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_searchNameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameInputMethodTextChanged

    private void RestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoreActionPerformed
        boolean restoration = BinManager.restoreItem(productStored, productListTable, bin);
        
        if(restoration){
           JOptionPane.showMessageDialog(this, "The item has been restored", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "There are no items to be restored", "Warning", JOptionPane.WARNING_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_RestoreActionPerformed

    private void itemCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemCategoryItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            String category = itemCategory.getSelectedItem().toString();
            categoryStored = new CategoryStored(productStored.getAllProducts());
            if (category.equalsIgnoreCase("All")) {
            
                ArrayList<Product> allProducts = productStored.getAllProducts();
            
                if (allProducts != null) {
                    TotalItems.setText(String.valueOf(allProducts.size()));
                    productStored.populatingTable(productListTable, allProducts);
                } 
                else {
                    TotalItems.setText("0");
                    productStored.populatingTable(productListTable, new ArrayList<Product>());
                }
                
            }
            else{
                LinkedList<Product> categoryProducts = categoryStored.getByCategory(category);
                
                if (categoryProducts != null && !categoryProducts.isEmpty()) {
                    TotalItems.setText(String.valueOf(categoryProducts.size()));
            }
                else{
                    TotalItems.setText("0");
                }
        }    
        }// TODO add your handling code here:
    }//GEN-LAST:event_itemCategoryItemStateChanged
    
    
    private void comboData(){
        comboDay.removeAllItems();
        comboMonth.removeAllItems();
        comboYear.removeAllItems();
      
        comboYear.addItem("0");
        for(int i = 1; i <= 31; i++){
            comboDay.addItem(String.valueOf(i));
        }
        for(int i = 1; i <= 12; i++){
            comboMonth.addItem(String.valueOf(i));
        }
        for(int i = 2000; i <= 2030; i++){
            comboYear.addItem(String.valueOf(i));
        }
        
    }
    
    private void searchItem(){
        String userInput = searchName.getText().toLowerCase().trim();
        ArrayList<Product> allProducts = productStored.getAllProducts();
        if(userInput.isEmpty()){
            productStored.populatingTable(productListTable, allProducts);
            return;
        }
        ArrayList<Product> searchContents = new ArrayList<>();
        for (Product product : allProducts) {
            if(product.getProductName().toLowerCase().contains(userInput)){
                searchContents.add(product);
            }
        }
        productStored.populatingTable(productListTable, searchContents);
    }
    
    private void searchAction(){
        searchName.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchItem();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                searchItem();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                searchItem();
            }
            });
    }
    private void TotalItemText(){
        itemCategory.setSelectedItem("All");
        ArrayList<Product> allProducts = productStored.getAllProducts();
        if (allProducts != null) {
            TotalItems.setText(String.valueOf(allProducts.size()));
            productStored.populatingTable(productListTable, allProducts);
        }
        else {
            TotalItems.setText("0");
            productStored.populatingTable(productListTable, new ArrayList<Product>());
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton Restore;
    private javax.swing.JLabel TotalItems;
    private javax.swing.JPanel addProduct;
    private javax.swing.JTable bin;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JComboBox<String> comboDay;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton idButton;
    private javax.swing.JTextField idSearch;
    private javax.swing.JComboBox<String> itemCategory;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField priceStr;
    private javax.swing.JTextField productId;
    private javax.swing.JTable productListTable;
    private javax.swing.JTextField productName;
    private javax.swing.JPanel productNum;
    private javax.swing.JTextField quantity;
    private javax.swing.JTable recentlyAdded;
    private javax.swing.JButton removeFromBin;
    private javax.swing.JTextField searchName;
    private javax.swing.JComboBox<String> sortBy;
    private javax.swing.JButton update;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JButton view;
    private javax.swing.JPanel viewProduct;
    // End of variables declaration//GEN-END:variables
}
