/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 * The class login is used to differentiate user or admin
 * The visitor gets admin access if they enter admin's credentials i.e. (username = Admin) and (password = admin)
 * The visitor gets user access if they enter user's credentials i.e. (username = User) and (password = user)
 * @author ruzalrajopadhyay
 */
import javax.swing.*;
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private Admin adminPage;
    private User userPage;
    
    
    
    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        adminMessage = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inventoryIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        enterDetail = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        loginSubmit = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(244, 179, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 17)); // NOI18N
        message.setText("Your Credentials To Continue Exploring!!!");
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 320, -1));

        adminMessage.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 13)); // NOI18N

        jLabel9.setText("We are here to minimize your efforts in inventory managing");

        jLabel10.setText("and expand your business globally.");

        javax.swing.GroupLayout adminMessageLayout = new javax.swing.GroupLayout(adminMessage);
        adminMessage.setLayout(adminMessageLayout);
        adminMessageLayout.setHorizontalGroup(
            adminMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMessageLayout.createSequentialGroup()
                .addGroup(adminMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminMessageLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel9))
                    .addGroup(adminMessageLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel10)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        adminMessageLayout.setVerticalGroup(
            adminMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMessageLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(36, 36, 36))
        );

        jPanel1.add(adminMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 550, -1));

        inventoryIcon.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        inventoryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vecteezy-warehouse-workers-effic.png"))); // NOI18N
        jPanel1.add(inventoryIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 230, 170));

        jPanel2.setBackground(new java.awt.Color(143, 1, 119));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterDetail.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 20)); // NOI18N
        enterDetail.setForeground(new java.awt.Color(255, 255, 255));
        enterDetail.setText("Enter Your Details");
        jPanel2.add(enterDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");
        jPanel2.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        username.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 13)); // NOI18N
        username.setMinimumSize(new java.awt.Dimension(64, 120));
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 80, -1));

        usernameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username:");
        jPanel2.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        password.setMinimumSize(new java.awt.Dimension(64, 120));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 80, -1));

        loginSubmit.setText("Submit");
        loginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(loginSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitActionPerformed
        // Declaring variables and initializing them with the value of jTextField
        String userName = username.getText();
        String pass = new String(password.getPassword());

        // Comparing to see whether the text field is empty or not
        if(userName.isEmpty() || pass.isEmpty()){
            JOptionPane.showMessageDialog(this,
                "Please fill all fields.",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
        }
        // admin credentials
        else if(userName.equalsIgnoreCase("admin") && pass.equals("admin")){
            if (adminPage == null) {
                adminPage = new Admin(this);
            }
            adminPage.setVisible(true);
            this.setVisible(false);
            
        }
        // users credentials
        else if(userName.equalsIgnoreCase("user") && pass.equals("user")){
            if(userPage == null) {
            userPage = new User(this);
            }
            userPage.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter correct information", "Invalid", JOptionPane.WARNING_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_loginSubmitActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // making the login page visible for the user
        Login login = new Login();
        login.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminMessage;
    private javax.swing.JLabel enterDetail;
    private javax.swing.JLabel inventoryIcon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginSubmit;
    private javax.swing.JLabel message;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
